--- #YAML:1.0
name:               Mojolicious-Plugin-WWWSession
version:            0.01
abstract:           WWW:Session sessions for Mojolicious
author:
    - Gligan Calin Horea <gliganh@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::MD5:          0
    Mojolicious::Plugin:  0
    Test::More:           0
    WWW::Session:         0.03
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
